apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        uid: victoriametrics
        type: prometheus
        access: proxy
        url: http://victoria-metrics.default.svc.cluster.local:8428
        isDefault: true
        editable: false
      - name: VictoriaTraces
        uid: victoriatraces
        type: jaeger
        access: proxy
        url: http://victoria-traces.default.svc.cluster.local:10428/select/jaeger
        editable: false
        jsonData:
          tracesToMetrics:
            datasourceUid: victoriametrics
            tags:
              - key: service.name
                value: service_name
            queries:
              - name: Request rate
                query: 'sum(rate(traces_span_metrics_calls_total{${__tags}}[5m]))'
              - name: Error rate
                query: 'sum(rate(traces_span_metrics_calls_total{${__tags},status_code="STATUS_CODE_ERROR"}[5m]))'
      - name: VictoriaLogs
        uid: victorialogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://victoria-logs.default.svc.cluster.local:9428
        editable: false
