apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-data
  namespace: default
spec:
  storageClassName: manual
  volumeName: victoria-metrics-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
