apiVersion: v1
kind: Service
metadata:
  name: victoria-traces
  namespace: default
  labels:
    app: victoria-traces
spec:
  type: ClusterIP
  selector:
    app: victoria-traces
  ports:
  - name: http
    port: 10428
    targetPort: 10428
    protocol: TCP