app:
  image:
    repository: mahammadalii12/observe
    tag: v7
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

collector:
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: v6
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

victoriaMetrics:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v6
  retentionPeriod: 7d
  pv:
    storage: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

victoriaLogs:
  image:
    repository: victoriametrics/victoria-logs
    tag: v6
  retentionPeriod: 7d
  pv:
    storage: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

victoriaTraces:
  image:
    repository: victoriametrics/victoria-traces
    tag: v6
  retentionPeriod: 7d
  pv:
    storage: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

grafana:
  image:
    repository: grafana/grafana
    tag: v6
  pv:
    storage: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 750Mi
