apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-logs-data
  namespace: default
spec:
  storageClassName: manual
  volumeName: victoria-logs-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.victoriaLogs.pv.storage }}
