apiVersion: v1
kind: Service
metadata:
  name: victoria-logs
  namespace: default
  labels:
    app: victoria-logs
spec:
  type: ClusterIP
  selector:
    app: victoria-logs
  ports:
  - name: http
    port: 9428
    targetPort: 9428
    protocol: TCP
