apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: mahammadalii12/observe:v3
        imagePullPolicy: Always
        name: observe
        env:
        - name: OTEL_SERVICE_NAME
          value: observe
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=observe
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.default.svc.cluster.local:4317
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
status: {}
