apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoria-logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/observability/victoria-logs
    type: DirectoryOrCreate
